[PHP]
extension_dir = "ext"
date.timezone = UTC
memory_limit = -1
display_errors = On
display_startup_errors = On
error_reporting = E_ALL

extension=curl
extension=fileinfo
extension=intl
extension=mbstring
extension=mysqli
extension=openssl
extension=pdo_mysql
extension=pdo_sqlite
extension=sodium
extension=sqlite3
extension=zip
