<?php

namespace App\Services\Documents;

use App\DTOs\Documents\StoredSignedDocument;
use App\Exceptions\ApiProblemException;
use Illuminate\Support\Str;
use Throwable;

class SignedDocumentStorage
{
    public function __construct(
        private readonly DocumentBlobVerifier $verifier,
        private readonly DocumentPrivateFilesystem $filesystem,
    ) {}

    public function store(string $generatedPath): StoredSignedDocument
    {
        $output = $input = null;
        $path = null;
        $ownedIdentity = null;
        try {
            $disk = (string) config('document_signing.storage_disk');
            if (config("filesystems.disks.{$disk}.driver") !== 'local' || config("filesystems.disks.{$disk}.visibility") !== 'private'
                || ! in_array($disk, config('document_versions.allowed_disks', []), true)) {
                throw new \RuntimeException('Private local storage is required.');
            }
            // Constructing Laravel's local adapter eagerly creates its root. Read
            // configuration directly so validation always precedes mutation.
            $configuredRoot = config("filesystems.disks.{$disk}.root");
            if (! is_string($configuredRoot)) {
                throw new \RuntimeException('A private storage root is required.');
            }
            $root = rtrim($configuredRoot, '/\\');
            // Validate exposure and aliases before creating a directory or file.
            $publicRoots = [public_path(), storage_path('app/public')];
            foreach (config('filesystems.disks', []) as $configuration) {
                if (($configuration['visibility'] ?? null) === 'public' && ($configuration['driver'] ?? null) === 'local') {
                    $publicRoots[] = $configuration['root'];
                }
            }
            foreach ($publicRoots as $publicRoot) {
                if ($this->overlaps($root, $publicRoot)
                    || (($resolved = realpath($publicRoot)) !== false && $this->overlaps($root, $resolved))) {
                    throw new \RuntimeException('Public storage is forbidden.');
                }
            }
            foreach ([config('filesystems.disks.project-imports.root'), config('signature_assets.storage_root'), config('signature_assets.temporary_directory')] as $other) {
                if (is_string($other) && ($this->overlaps($root, $other)
                    || (($resolved = realpath($other)) !== false && $this->overlaps($root, $resolved)))) {
                    throw new \RuntimeException('A distinct generated-document namespace is required.');
                }
            }
            $this->filesystem->prepareDirectory($root);
            $relative = Str::uuid().'.pdf';
            $candidate = $root.DIRECTORY_SEPARATOR.$relative;
            $output = @fopen($candidate, 'x+b');
            if (! is_resource($output)) {
                throw new \RuntimeException('Exclusive creation failed.');
            }
            $path = $candidate; // Only an exclusively owned file may be removed on failure.
            $ownedIdentity = fstat($output);
            if (! @chmod($path, 0600)) {
                throw new \RuntimeException('Private file creation failed.');
            }
            $this->filesystem->assertPrivateFile($path);
            $this->verifier->resolvePrivatePath($disk, $relative);
            $input = @fopen($generatedPath, 'rb');
            if (! is_resource($input)) {
                throw new \RuntimeException('Generated bytes are missing.');
            }
            $sourceIdentity = fstat($input);
            if ($sourceIdentity === false || ($sourceIdentity['mode'] & 0170000) !== 0100000
                || $sourceIdentity['size'] < 8 || $sourceIdentity['size'] > config('document_signing.max_pdf_bytes')) {
                throw new \RuntimeException('Generated PDF is invalid.');
            }
            $bytes = 0;
            $sample = '';
            $hash = hash_init('sha256');
            while (! feof($input)) {
                $chunk = fread($input, 65536);
                if ($chunk === false || ($chunk === '' && ! feof($input))) {
                    throw new \RuntimeException('Generated bytes cannot be read.');
                }
                $bytes += strlen($chunk);
                if ($bytes > config('document_signing.max_pdf_bytes')) {
                    throw new \RuntimeException('Generated PDF exceeds limit.');
                }
                hash_update($hash, $chunk);
                if (strlen($sample) < 8192) {
                    $sample .= substr($chunk, 0, 8192 - strlen($sample));
                }
                $offset = 0;
                while ($offset < strlen($chunk)) {
                    $written = fwrite($output, substr($chunk, $offset));
                    if ($written === false || $written === 0) {
                        throw new \RuntimeException('Generated bytes cannot be stored.');
                    }
                    $offset += $written;
                }
            }
            if ($bytes !== $sourceIdentity['size'] || ! $this->sameIdentity($sourceIdentity, fstat($input))
                || (new \finfo(FILEINFO_MIME_TYPE))->buffer($sample) !== 'application/pdf'
                || ! fflush($output) || ! fsync($output)) {
                throw new \RuntimeException('Generated bytes cannot be finalized.');
            }
            $identity = fstat($output);
            $sha256 = hash_final($hash);
            if ($identity === false || fseek($output, 0) !== 0) {
                throw new \RuntimeException('Stored identity is unavailable.');
            }
            $readback = hash_init('sha256');
            if (hash_update_stream($readback, $output) !== $bytes || ! hash_equals($sha256, hash_final($readback))) {
                throw new \RuntimeException('Stored bytes differ from the generated PDF.');
            }
            $this->filesystem->assertCanonicalPath($root);
            $this->filesystem->assertPrivateDirectory($root);
            $this->filesystem->assertPrivateFile($path);
            $this->verifier->resolvePrivatePath($disk, $relative);
            clearstatcache(true, $path);
            if (! $this->sameIdentity($identity, @lstat($path)) || ! $this->sameIdentity($identity, fstat($output))) {
                throw new \RuntimeException('Stored identity changed.');
            }

            return new StoredSignedDocument($disk, $relative, $path, $bytes, $sha256, $identity);
        } catch (Throwable) {
            if (is_resource($output)) {
                $current = fstat($output);
                // Capture the completed or partial owned handle before closing it.
                if ($ownedIdentity !== false && $ownedIdentity !== null && $current !== false
                    && $ownedIdentity['dev'] === $current['dev'] && $ownedIdentity['ino'] === $current['ino']) {
                    $ownedIdentity = $current;
                }
                fclose($output);
                $output = null;
            }
            clearstatcache();
            if ($path !== null && is_array($ownedIdentity) && $this->sameIdentity($ownedIdentity, @lstat($path))) {
                @unlink($path);
            }
            throw new ApiProblemException('The signed PDF could not be stored.', 'document_signing_storage_failed', 503);
        } finally {
            if (is_resource($input)) fclose($input);
            if (is_resource($output)) fclose($output);
        }
    }

    /** Called only after a definite rollback, never following an uncertain commit. */
    public function rollback(StoredSignedDocument $file): void
    {
        clearstatcache(true, $file->path);
        $current = @lstat($file->path);
        if (! $this->sameIdentity($file->identity, $current)) return;
        if (hash_equals($file->sha256, (string) @hash_file('sha256', $file->path))) {
            @unlink($file->path);
        }
    }

    private function sameIdentity(array $expected, array|false $actual): bool
    {
        if ($actual === false || ($actual['mode'] & 0170000) !== 0100000 || ($actual['nlink'] ?? 0) !== 1) return false;
        foreach (['dev', 'ino', 'mode', 'size', 'mtime', 'ctime'] as $key) {
            if ($expected[$key] !== $actual[$key]) return false;
        }

        return true;
    }

    private function overlaps(string $one, string $two): bool
    {
        $one = $this->normalize($one).'/';
        $two = $this->normalize($two).'/';

        return str_starts_with($one, $two) || str_starts_with($two, $one);
    }

    private function normalize(string $path): string
    {
        $normalized = rtrim(str_replace('\\', '/', $path), '/');

        return DIRECTORY_SEPARATOR === '\\' ? strtolower($normalized) : $normalized;
    }
}
