<?php

namespace Tests\Feature;

use App\Exceptions\ApiProblemException;
use App\Services\Documents\DocumentBlobVerifier;
use App\Services\Documents\DocumentPrivateFilesystem;
use App\Models\DocumentVersion;
use App\Services\Documents\SignedDocumentStorage;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use PHPUnit\Framework\Attributes\DataProvider;
use Symfony\Component\Process\Process;
use Tests\TestCase;

class SignedDocumentStorageTest extends TestCase
{
    private string $directory;

    private string $source;

    private string $root;

    private string $pdf = "%PDF-1.7\n1 0 obj\n<< /Type /Catalog >>\nendobj\n%%EOF\n";

    protected function setUp(): void
    {
        parent::setUp();
        $this->directory = storage_path('framework/testing/signed-documents-'.Str::uuid());
        File::ensureDirectoryExists($this->directory, 0700);
        $this->root = $this->directory.DIRECTORY_SEPARATOR.'private';
        $this->source = $this->directory.DIRECTORY_SEPARATOR.'generated.pdf';
        file_put_contents($this->source, $this->pdf);
        config(['filesystems.disks.signed-documents.root' => $this->root]);
        Storage::forgetDisk('signed-documents');
        $this->beforeApplicationDestroyed(function (): void {
            Storage::forgetDisk('signed-documents');
            Storage::forgetDisk('local');
            File::deleteDirectory($this->directory);
        });
    }

    public function test_private_exclusive_file_has_verified_checksum_and_cannot_be_aliased_through_local_disk(): void
    {
        $storage = app(SignedDocumentStorage::class);
        $stored = $storage->store($this->source);
        $this->assertSame($this->pdf, file_get_contents($stored->path));
        $this->assertSame(hash('sha256', $this->pdf), $stored->sha256);
        $this->assertSame(strlen($this->pdf), $stored->sizeBytes);
        $this->assertSame($this->pdf, file_get_contents($this->source));
        $this->assertSame('signed-documents', $stored->disk);
        $this->assertSame(realpath($stored->path), app(DocumentBlobVerifier::class)->resolvePrivatePath($stored->disk, $stored->storagePath));
        config(['filesystems.disks.local.root' => $this->directory]);
        Storage::forgetDisk('local');
        try {
            app(DocumentBlobVerifier::class)->resolvePrivatePath('local', 'private/'.$stored->storagePath);
            $this->fail('The broad local disk exposed a generated-document alias.');
        } catch (ApiProblemException $exception) {
            $this->assertSame('document_version_storage_invalid', $exception->errorCode);
        }
        $storage->rollback($stored);
        $this->assertFileDoesNotExist($stored->path);
        $this->assertFileExists($this->source);
    }

    public function test_rollback_never_removes_changed_content_and_failure_removes_only_its_owned_output(): void
    {
        $storage = app(SignedDocumentStorage::class);
        $stored = $storage->store($this->source);
        $changed = str_replace('Catalog', 'Changed', $this->pdf);
        file_put_contents($stored->path, $changed);
        $storage->rollback($stored);
        $this->assertSame($changed, file_get_contents($stored->path));
        file_put_contents($this->source, 'This is not a generated PDF.');
        try {
            $storage->store($this->source);
            $this->fail('Non-PDF generated bytes were accepted.');
        } catch (ApiProblemException $exception) {
            $this->assertSame('document_signing_storage_failed', $exception->errorCode);
        }
        $this->assertCount(1, File::files($this->root));
        $this->assertSame($changed, file_get_contents($stored->path));
    }

    public function test_public_and_existing_insecure_roots_fail_closed_before_file_creation(): void
    {
        config(['filesystems.disks.signed-documents.root' => public_path('signed-documents-test-'.Str::uuid())]);
        Storage::forgetDisk('signed-documents');
        try {
            app(SignedDocumentStorage::class)->store($this->source);
            $this->fail('Public generated-file storage was accepted.');
        } catch (ApiProblemException $exception) {
            $this->assertSame('document_signing_storage_failed', $exception->errorCode);
            $this->assertDirectoryDoesNotExist(config('filesystems.disks.signed-documents.root'));
        }
        mkdir($this->root, 0777);
        if (PHP_OS_FAMILY !== 'Windows') {
            chmod($this->root, 0777);
        }
        config(['filesystems.disks.signed-documents.root' => $this->root]);
        Storage::forgetDisk('signed-documents');
        try {
            app(SignedDocumentStorage::class)->store($this->source);
            $this->fail('An existing insecure directory was silently repaired or accepted.');
        } catch (ApiProblemException $exception) {
            $this->assertSame('document_signing_storage_failed', $exception->errorCode);
        }
        $this->assertSame([], File::files($this->root));
    }

    #[DataProvider('invalidRootSegments')]
    public function test_invalid_roots_are_rejected_before_adapter_or_directory_creation(string $suffix): void
    {
        config(['filesystems.disks.signed-documents.root' => $this->root.$suffix]);
        $this->assertStorageFailure();
        $this->assertSame(['generated.pdf'], array_values(array_diff(scandir($this->directory), ['.', '..'])));
        $this->assertSame($this->pdf, file_get_contents($this->source));
    }

    public static function invalidRootSegments(): array
    {
        return [
            'parent traversal' => ['/../escaped'],
            'current-directory alias' => ['/./child'],
            'Windows trailing-dot alias' => ['./child'],
            'Windows alternate data stream' => [':stream/child'],
            'Windows reserved device' => ['/NUL/child'],
        ];
    }

    #[DataProvider('dedicatedNamespaces')]
    public function test_other_private_namespaces_are_rejected_before_missing_directories_are_created(string $configuration): void
    {
        config([$configuration => $this->root.DIRECTORY_SEPARATOR.'existing-namespace']);
        $this->assertStorageFailure();
        $this->assertDirectoryDoesNotExist($this->root);
        config([$configuration => $this->root]);
        config(['filesystems.disks.signed-documents.root' => $this->root.DIRECTORY_SEPARATOR.'generated']);
        $this->assertStorageFailure();
        $this->assertDirectoryDoesNotExist($this->root);
    }

    public static function dedicatedNamespaces(): array
    {
        return [
            'imports' => ['filesystems.disks.project-imports.root'],
            'signature assets' => ['signature_assets.storage_root'],
            'signature workspace' => ['signature_assets.temporary_directory'],
        ];
    }

    public function test_windows_junction_ancestor_is_rejected_before_creating_or_changing_target_content(): void
    {
        if (PHP_OS_FAMILY !== 'Windows') {
            $this->markTestSkipped('Windows junction validation requires Windows.');
        }
        $target = $this->directory.DIRECTORY_SEPARATOR.'target';
        $alias = $this->directory.DIRECTORY_SEPARATOR.'alias';
        mkdir($target, 0700);
        file_put_contents($target.DIRECTORY_SEPARATOR.'sentinel', 'unchanged target bytes');
        $this->assertSame($this->directory, dirname($alias));
        $this->assertSame($this->directory, dirname($target));
        $this->fixturePowershell(
            '$item=New-Item -ItemType Junction -Path $env:SIGNED_FIXTURE_ALIAS -Target $env:SIGNED_FIXTURE_TARGET; if(($item.Attributes -band [IO.FileAttributes]::ReparsePoint) -eq 0){throw "Fixture is not a junction"}',
            ['SIGNED_FIXTURE_ALIAS' => $alias, 'SIGNED_FIXTURE_TARGET' => $target],
        );
        try {
            config(['filesystems.disks.signed-documents.root' => $alias.DIRECTORY_SEPARATOR.'missing-child']);
            $this->assertStorageFailure();
            $this->assertSame(['sentinel'], array_values(array_diff(scandir($target), ['.', '..'])));
            $this->assertSame('unchanged target bytes', file_get_contents($target.DIRECTORY_SEPARATOR.'sentinel'));
        } finally {
            // Remove only this checked link; never recursively traverse its target.
            $this->assertSame($this->directory, dirname($alias));
            $this->fixturePowershell(
                '$item=Get-Item -Force -LiteralPath $env:SIGNED_FIXTURE_ALIAS; if($item.FullName -ne [IO.Path]::GetFullPath($env:SIGNED_FIXTURE_ALIAS) -or ($item.Attributes -band [IO.FileAttributes]::ReparsePoint) -eq 0){throw "Refusing non-junction cleanup"}; [IO.Directory]::Delete($item.FullName)',
                ['SIGNED_FIXTURE_ALIAS' => $alias],
            );
        }
    }

    public function test_windows_broadened_file_acl_blocks_signed_download_and_broadened_snapshot_root_blocks_copy(): void
    {
        if (PHP_OS_FAMILY !== 'Windows') {
            $this->markTestSkipped('Windows DACL enforcement requires Windows.');
        }
        $stored = app(SignedDocumentStorage::class)->store($this->source);
        $version = new DocumentVersion([
            'storage_disk' => $stored->disk, 'storage_path' => $stored->storagePath,
            'size_bytes' => $stored->sizeBytes, 'sha256' => $stored->sha256,
            'mime_type' => 'application/pdf', 'original_name' => 'signed.pdf',
        ]);
        $snapshots = $this->directory.DIRECTORY_SEPARATOR.'snapshots';
        config(['document_versions.temporary_directory' => $snapshots]);
        $file = app(DocumentBlobVerifier::class)->verifyVersionToTemporaryFile($version);
        app(DocumentPrivateFilesystem::class)->assertPrivateFile($file->path);
        $this->assertSame($this->pdf, stream_get_contents($file->stream()));
        $file->close();
        $accessOnly = '$section=[Security.AccessControl.AccessControlSections]::Access; $sddl=(Get-Acl -LiteralPath $env:ACL_FIXTURE_PATH).GetSecurityDescriptorSddlForm($section); $isDirectory=[IO.Directory]::Exists($env:ACL_FIXTURE_PATH); if($isDirectory){$acl=New-Object Security.AccessControl.DirectorySecurity}else{$acl=New-Object Security.AccessControl.FileSecurity}; $acl.SetSecurityDescriptorSddlForm($sddl,$section); ';
        $persist = 'if($isDirectory){[IO.Directory]::SetAccessControl($env:ACL_FIXTURE_PATH,$acl)}else{[IO.File]::SetAccessControl($env:ACL_FIXTURE_PATH,$acl)}';
        $script = $accessOnly.'$sid=New-Object Security.Principal.SecurityIdentifier("S-1-1-0"); $rule=New-Object Security.AccessControl.FileSystemAccessRule($sid,"Read","Allow"); $acl.AddAccessRule($rule); '.$persist;
        $this->fixturePowershell($script, ['ACL_FIXTURE_PATH' => $stored->path]);
        try {
            app(DocumentBlobVerifier::class)->verifyVersionToTemporaryFile($version);
            $this->fail('A signed file with Everyone access was downloaded.');
        } catch (ApiProblemException $exception) {
            $this->assertSame('document_version_storage_invalid', $exception->errorCode);
        }
        $this->fixturePowershell($accessOnly.'$sid=New-Object Security.Principal.SecurityIdentifier("S-1-1-0"); $acl.PurgeAccessRules($sid); '.$persist, ['ACL_FIXTURE_PATH' => $stored->path]);
        $this->fixturePowershell($script, ['ACL_FIXTURE_PATH' => $snapshots]);
        try {
            app(DocumentBlobVerifier::class)->verifyVersionToTemporaryFile($version);
            $this->fail('An insecure snapshot directory was silently repaired or used.');
        } catch (ApiProblemException $exception) {
            $this->assertSame('document_version_download_unavailable', $exception->errorCode);
        }
        $this->assertSame([], File::files($snapshots));
        $this->assertSame($this->pdf, file_get_contents($stored->path));
    }

    private function assertStorageFailure(): void
    {
        Storage::forgetDisk('signed-documents');
        try {
            app(SignedDocumentStorage::class)->store($this->source);
            $this->fail('An invalid generated-document root was accepted.');
        } catch (ApiProblemException $exception) {
            $this->assertSame('document_signing_storage_failed', $exception->errorCode);
            $this->assertSame(503, $exception->status);
        }
    }

    private function fixturePowershell(string $script, array $environment): void
    {
        $process = new Process(['powershell.exe', '-NoLogo', '-NoProfile', '-NonInteractive', '-Command', '$ErrorActionPreference="Stop"; '.$script], null, $environment);
        $process->setTimeout(15);
        $process->run();
        $this->assertTrue($process->isSuccessful(), 'Windows fixture operation failed: '.$process->getErrorOutput());
    }
}
